pipeline {
    agent any
    stages {
        stage('Build') {
            when {
                expression {
                    return params.current_status == "opened" && params.merged == false
                }
            }
            steps {
                sh 'pwd'
                sh 'ls'
                dir("Docker") {
                    sh 'ls'
                    sh 'mvn -B -DskipTests clean package' 
                }
            }
        }
        stage('Test') {
            when {
                expression {
                    return params.current_status == "opened" && params.merged == false
                }
            }
            environment {
                TEXT= "hello"
            }
            steps {
                dir("Docker") {
                    sh 'ls'
                    sh 'mvn test'
                }
            }
        }
        stage('Build after merge') {
            when {
                allOf {
                    branch 'master'
                }
            }
            steps {
                sh 'pwd'
                sh 'ls'
                dir("Docker") {
                    sh 'ls'
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
    }
}
