pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'pwd'
                sh 'ls'
                dir("Docker") {
                    sh 'ls'
                    sh 'mvn -B -DskipTests clean package' 
                }
            }
        }
        stage('Test') {
            environmnet {
                TEXT= "hello"
            }
            steps {
                dir("Docker") {
                    sh 'ls'
                    sh 'mvn test'
                }
            }
        }
    }
}
