# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
#   push:
#     branches: CI/CD_Pipeline
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env:
        TEXT: ${{ secrets.TEXT }}
      run: cd Docker && mvn -B package --file pom.xml && ls target/
#     - name: Maven Verify
#       env:
#         TEXT: ${{ secrets.TEXT }}
#       run: cd Docker && mvn -B clean verify
#   docker:
    - name: Publish - Docker Hub
      env:
        REPO: ${{ secrets.DOCKER_REPO }} 
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    - name: Build Docker image
      run: cd Docker && docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
    - name: Publish Docker image
      run: docker push $REPO
